-- روابط السوشيال ميديا (قائمة ديناميكية) داخل site_content → contact.socialItems
--
-- مثال:
-- "socialItems": [
--   { "id": "uuid-1", "platform": "tiktok", "url": "https://tiktok.com/@yourpage" },
--   { "id": "uuid-2", "platform": "snapchat", "url": "https://snapchat.com/add/you" },
--   { "id": "uuid-3", "platform": "custom", "label": "Threads", "url": "https://threads.net/@you" }
-- ]
--
-- المنصات المدعومة: facebook, instagram, twitter, whatsapp, tiktok, snapchat,
-- youtube, linkedin, telegram, pinterest, custom
